// ─── Shared Posts Data ────────────────────────────────────────────────────────

export const POSTS = [
  {
    id: "1",
    author: {
      name: "Hexa Media",
      handle: "@hexamedia",
      verified: true,
      hasLeaf: true,
      badge: "HM",
      badgeColor: "#3B82F6",
      avatar: "https://res.cloudinary.com/dkqdwcguu/image/upload/c_crop,w_512,h_512,g_auto/v1754275277/joy_img_3_ony3do.jpg",
    },
    timeAgo: "12 minutes",
    title: "Reimagining African NGOs: From Survival to Sustainability",
    description: "Join World NGO Day Live Webinar",
    content: "Join World NGO Day Live Webinar to discuss new strategies.",
    image: "https://res.cloudinary.com/dkqdwcguu/image/upload/v1766617857/SSA_hpyhkb.jpg",
    likes: 50,
    comments: 210,
    shares: 8,
    liked: false,
    saved: false,
    tags: ["#NGO", "#Africa", "#Sustainability"],
    isFollowing: true,
    isTrending: true,
  },
  {
    id: "2",
    author: {
      name: "Serenity",
      handle: "@serenity",
      verified: false,
      hasLeaf: false,
      badge: "SR",
      badgeColor: "#EC4899",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    timeAgo: "12 minutes",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
    image: null,
    likes: 24,
    comments: 15,
    shares: 2,
    liked: true,
    saved: true,
    tags: ["#Lifestyle", "#Wellness"],
    isFollowing: true,
    isTrending: false,
  },
  {
    id: "3",
    author: {
      name: "Sarah Johnson",
      handle: "@sarahj",
      verified: true,
      badge: "SJ",
      badgeColor: "#FF6B6B",
      avatar: "👩‍💼",
    },
    timeAgo: "2h ago",
    title: "AI Design Revolution",
    description: "Just launched our new AI-powered design tool. The response has been amazing! 🚀",
    content: "Just launched our new AI-powered design tool. The response has been amazing! 🚀",
    image: null,
    likes: 2450,
    comments: 312,
    shares: 890,
    liked: false,
    saved: false,
    tags: ["#Design", "#AI", "#Tech"],
    isFollowing: true,
    isTrending: false,
  },
  {
    id: "4",
    author: {
      name: "Alex Rivera",
      handle: "@alexrivera",
      verified: true,
      badge: "AR",
      badgeColor: "#4ECDC4",
      avatar: "👨‍🎨",
    },
    timeAgo: "4h ago",
    title: "Golden Gate Sunset",
    description: "Beautiful sunset at the Golden Gate Bridge. Nature never ceases to amaze me 🌅",
    content: "Beautiful sunset at the Golden Gate Bridge. Nature never ceases to amaze me 🌅",
    image: "https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?q=80&w=1000",
    likes: 5630,
    comments: 487,
    shares: 1200,
    liked: true,
    saved: true,
    tags: ["#Photography", "#Travel"],
    isFollowing: true,
    isTrending: true,
  },
  {
    id: "5",
    author: {
      name: "Emma Chen",
      handle: "@emmachen",
      verified: false,
      badge: "EC",
      badgeColor: "#95E1D3",
      avatar: "👩‍💻",
    },
    timeAgo: "6h ago",
    title: "Machine Learning Guide",
    description: "Sharing my journey into machine learning. Check out this comprehensive guide I wrote 📚",
    content: "Sharing my journey into machine learning. Check out this comprehensive guide I wrote 📚",
    image: null,
    likes: 3200,
    comments: 256,
    shares: 650,
    liked: false,
    saved: true,
    tags: ["#MachineLearning", "#Education"],
    isFollowing: false,
    isTrending: false,
  }
];

export const CATEGORIES = [
  { id: "1", label: "All Posts", icon: "📰", route: "all-posts" },
  { id: "2", label: "Following", icon: "👥", route: "following" },
  { id: "3", label: "Trending", icon: "🔥", route: "trending" },
  { id: "4", label: "Entertainment & Pop Culture", icon: "🎬", route: "entertainment" },
  { id: "5", label: "Saved posts", icon: "🔖", route: "saved-posts" },
];

export default { POSTS, CATEGORIES };
