// ─── Shared Posts Data ────────────────────────────────────────────────────────

export const POSTS = [
  {
    id: "1",
    author: {
      name: "Sarah Johnson",
      handle: "@sarahj",
      verified: true,
      badge: "SJ",
      badgeColor: "#FF6B6B",
      avatar: "👩‍💼",
    },
    timeAgo: "2h ago",
    content:
      "Just launched our new AI-powered design tool. The response has been amazing! 🚀",
    image: null,
    likes: 2450,
    comments: 312,
    shares: 890,
    liked: false,
    saved: false,
    tags: ["#Design", "#AI", "#Tech"],
    isFollowing: true,
    isTrending: false,
  },
  {
    id: "2",
    author: {
      name: "Alex Rivera",
      handle: "@alexrivera",
      verified: true,
      badge: "AR",
      badgeColor: "#4ECDC4",
      avatar: "👨‍🎨",
    },
    timeAgo: "4h ago",
    content:
      "Beautiful sunset at the Golden Gate Bridge. Nature never ceases to amaze me 🌅",
    image: "🌅",
    likes: 5630,
    comments: 487,
    shares: 1200,
    liked: true,
    saved: true,
    tags: ["#Photography", "#Travel"],
    isFollowing: true,
    isTrending: true,
  },
  {
    id: "3",
    author: {
      name: "Emma Chen",
      handle: "@emmachen",
      verified: false,
      badge: "EC",
      badgeColor: "#95E1D3",
      avatar: "👩‍💻",
    },
    timeAgo: "6h ago",
    content:
      "Sharing my journey into machine learning. Check out this comprehensive guide I wrote 📚",
    image: null,
    likes: 3200,
    comments: 256,
    shares: 650,
    liked: false,
    saved: true,
    tags: ["#MachineLearning", "#Education"],
    isFollowing: false,
    isTrending: false,
  },
  {
    id: "4",
    author: {
      name: "Marcus Tech",
      handle: "@marcustech",
      verified: true,
      badge: "MT",
      badgeColor: "#FFD93D",
      avatar: "👨‍💻",
    },
    timeAgo: "8h ago",
    content:
      "Web3 adoption is accelerating faster than we anticipated. What's your take? 💭",
    image: null,
    likes: 1890,
    comments: 523,
    shares: 445,
    liked: false,
    saved: false,
    tags: ["#Web3", "#Crypto"],
    isFollowing: true,
    isTrending: true,
  },
  {
    id: "5",
    author: {
      name: "Jessica Lee",
      handle: "@jessicalee",
      verified: true,
      badge: "JL",
      badgeColor: "#A8E6CF",
      avatar: "👩‍🔬",
    },
    timeAgo: "10h ago",
    content:
      "Excited to announce our new research findings on sustainable energy! 🌱⚡",
    image: null,
    likes: 4120,
    comments: 389,
    shares: 920,
    liked: true,
    saved: false,
    tags: ["#Science", "#Energy", "#Sustainability"],
    isFollowing: true,
    isTrending: true,
  },
];

export const CATEGORIES = [
  { id: "1", label: "All Posts", icon: "📰", route: "all-posts" },
  { id: "2", label: "Following", icon: "👥", route: "following" },
  { id: "3", label: "Trending", icon: "🔥", route: "trending" },
  { id: "4", label: "Saved posts", icon: "🔖", route: "saved-posts" },
];
